version: '3.8'

services:
  athena_backend_neurosync:
    build:
      context: ./
      dockerfile: DockerFile.routeNeurosync
    container_name: athena_backend_neurosync_container
    ports:
      - "5000:5000"
    volumes:
      - .:/athena_backend_neurosync
    env_file: .env
    deploy:
      resources:
        reservation:
          devices:
          - driver: nvidia
            capabilities: [gpu]
            count: 1
  athena_backend_kokoro:
    build:
      context: ./
      dockerfile: DockerFile.routeKokoro
    container_name: athena_backend_kokoro_container
    ports:
      - "8000:8000"
    volumes:
      - .:/athena_backend_kokoro