FROM nvidia/cuda:12.8.1-runtime-ubuntu22.04

WORKDIR /athena_backend_neurosync

COPY requirements.txt .
RUN apt-get update && apt-get install -y ffmpeg libgl1 libsndfile1 git-lfs python3 python3-pip git git-lfs && \ git lfs install
RUN git clone https://github.com/PrajnyiqueG/digitalhuman.git && \
    cd digitalhuman &&\
    git lfs pull

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 5000

CMD [ "python", "NeuroSync_Local_API/neurosync_local_api.py"]

LABEL maintainer="prajnyique@theathenaai.com"
LABEL version="1.0"
LABEL description="Neurosync api route container"

