FROM python:3.10
FROM nvidia/cuda:12.8.1-runtime-ubuntu22.04

WORKDIR /athena_backend_neurosync

COPY requirements.txt .
RUN apt-get update && apt-get install -y ffmpeg libgl1 libsndfile1 git-lfs
RUN pip install --no-cache-dir -r requirements.txt

COPY ./NeuroSync_Local_API ./NeuroSync_Local_API
EXPOSE 5000

CMD [ "python", "NeuroSync_Local_API/neurosync_local_api.py"]

LABEL maintainer="prajnyique@theathenaai.com"
LABEL version="1.0"
LABEL description="Neurosync api route container"

