services:
  athena_backend_neurosync:
    build:
      context: ./
      dockerfile: DockerFile.routeNeurosync
    container_name: athena_backend_neurosync_container
    ports:
      - "5000:5000"
    # volumes:
    #   - .:/athena_backend_neurosync/digitalhuman/NeuroSync_Local_API
    env_file: .env
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
  athena_backend_kokoro:
    build:
      context: ./
      dockerfile: DockerFile.routeKokoro
    container_name: athena_backend_kokoro_container
    ports:
      - "8000:8000"
    volumes:
      - .:/athena_backend_kokoro